blank_issues_enabled: false
contact_links:
  - name: onezDBViewer Support
    url: https://github.com/onezloop/onezdbviewer/discussions
    about: Please ask and answer questions here.
  - name: Contact Us
    url: https://onezloop.com/#contact
    about: Have something to share? We'd love to hear from you.
